package spot

import "testing"

func TestNewSpotIsHumanByDefault(t *testing.T) {
	dx := "W1ABC"
	de := "K1XYZ"
	freq := 14074.5
	mode := "FT8"
	s := NewSpot(dx, de, freq, mode)
	if !s.IsHuman {
		t.Fatalf("NewSpot should mark the spot as human-generated by default")
	}
}

func TestNewSpotBeaconFlag(t *testing.T) {
	s := NewSpot("W1ABC/B", "K1XYZ", 14074.5, "CW")
	if !s.IsBeacon {
		t.Fatalf("NewSpot should mark DX calls ending in /B as beacons")
	}
	nonBeacon := NewSpot("W1ABC", "K1XYZ", 14074.5, "CW")
	if nonBeacon.IsBeacon {
		t.Fatalf("NewSpot should leave IsBeacon false for non-beacon callsigns")
	}
}

func TestRefreshBeaconFlagUsesComment(t *testing.T) {
	s := NewSpot("W1ABC", "K1XYZ", 14074.5, "CW")
	s.Comment = "Heard via NCDXF beacon schedule"
	s.RefreshBeaconFlag()
	if !s.IsBeacon {
		t.Fatalf("RefreshBeaconFlag should set IsBeacon when comment contains NCDXF")
	}

	s.Comment = "strong beacon signal"
	s.RefreshBeaconFlag()
	if !s.IsBeacon {
		t.Fatalf("RefreshBeaconFlag should set IsBeacon when comment contains BEACON")
	}

	s.Comment = "ordinary comment"
	s.RefreshBeaconFlag()
	if s.IsBeacon {
		t.Fatalf("RefreshBeaconFlag should clear IsBeacon when no indicators remain")
	}
}
